spring.datasource.username=beer_order_service
spring.datasource.password={cipher}8267329d7eba2d2e452c23e75d5cd06b0066d1a84eca3f3ca307b0744216f7e1
spring.datasource.url=jdbc:mariadb://127.0.0.1:3307/beerorderservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

spring.artemis.user=artemis
spring.artemis.password={cipher}d5956b03fbdca1883c87363ae623bd7886de6f378efd83926c2e86ccf113c215
